var = input('Digite algo: ')
print('O tipo primitivo é: {}'.format(type(var)))
print('É alfanumérico? {}'.format(var.isalnum()))
print('É alfabético? {}'.format(var.isalpha()))
print('É numérico? {}'.format(var.isnumeric()))
print('É decimal? {}'.format(var.isdecimal()))
print('É um dígito? {}'.format(var.isdigit()))
print('Está em minúculas? {}'.format(var.islower()))
print('Está em maiúsculas? {}'.format(var.isupper()))
print('É um capitalizado? {}'.format(var.istitle()))
print('É imprimível? {}'.format(var.isprintable()))
print('Só tem espaços? {}'.format(var.isspace()))
print('É um identificador? {}'.format(var.isidentifier()))
